/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sist_trenes;
import Carga.*;
import ds.desktop.notify.DesktopNotify;
import moduloRegistro.registroRecorridos;

import moduloServicio.menuReserva;

/**
 *
 * @author Usuario
 */
public class IntMenu extends javax.swing.JFrame {

    /**
     * Creates new form IntMenu
     */
 
    public IntMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelFondo = new javax.swing.JPanel();
        jPanelFondoImagen = new javax.swing.JPanel();
        jlblTitulo = new javax.swing.JLabel();
        jbtnRecorrido = new javax.swing.JButton();
        jbtnReserva = new javax.swing.JButton();
        jbtnReporte = new javax.swing.JButton();
        jbtnRegistrar = new javax.swing.JButton();
        jbtnConsulta = new javax.swing.JButton();
        jlblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setLayout(new java.awt.GridBagLayout());

        jPanelFondoImagen.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondoImagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblTitulo.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jlblTitulo.setForeground(java.awt.SystemColor.desktop);
        jlblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logotren2.png"))); // NOI18N
        jPanelFondoImagen.add(jlblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 420, 180));

        jbtnRecorrido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton7.png"))); // NOI18N
        jbtnRecorrido.setBorder(null);
        jbtnRecorrido.setBorderPainted(false);
        jbtnRecorrido.setContentAreaFilled(false);
        jbtnRecorrido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRecorrido.setFocusPainted(false);
        jbtnRecorrido.setFocusable(false);
        jbtnRecorrido.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton7press.png"))); // NOI18N
        jbtnRecorrido.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton7roll.png"))); // NOI18N
        jbtnRecorrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRecorridoActionPerformed(evt);
            }
        });
        jPanelFondoImagen.add(jbtnRecorrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 160, -1));

        jbtnReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton4.png"))); // NOI18N
        jbtnReserva.setBorder(null);
        jbtnReserva.setBorderPainted(false);
        jbtnReserva.setContentAreaFilled(false);
        jbtnReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnReserva.setFocusPainted(false);
        jbtnReserva.setFocusable(false);
        jbtnReserva.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton4press.png"))); // NOI18N
        jbtnReserva.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton4roll.png"))); // NOI18N
        jbtnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReservaActionPerformed(evt);
            }
        });
        jPanelFondoImagen.add(jbtnReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 220, 70));

        jbtnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton5.png"))); // NOI18N
        jbtnReporte.setBorder(null);
        jbtnReporte.setBorderPainted(false);
        jbtnReporte.setContentAreaFilled(false);
        jbtnReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnReporte.setFocusPainted(false);
        jbtnReporte.setFocusable(false);
        jbtnReporte.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton5press.png"))); // NOI18N
        jbtnReporte.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton5roll.png"))); // NOI18N
        jPanelFondoImagen.add(jbtnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 200, -1));

        jbtnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton8.png"))); // NOI18N
        jbtnRegistrar.setToolTipText("");
        jbtnRegistrar.setBorder(null);
        jbtnRegistrar.setBorderPainted(false);
        jbtnRegistrar.setContentAreaFilled(false);
        jbtnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRegistrar.setFocusPainted(false);
        jbtnRegistrar.setFocusable(false);
        jbtnRegistrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton8press.png"))); // NOI18N
        jbtnRegistrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton8roll.png"))); // NOI18N
        jbtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarActionPerformed(evt);
            }
        });
        jPanelFondoImagen.add(jbtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jbtnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton6.png"))); // NOI18N
        jbtnConsulta.setToolTipText("Consultar viaje");
        jbtnConsulta.setBorder(null);
        jbtnConsulta.setBorderPainted(false);
        jbtnConsulta.setContentAreaFilled(false);
        jbtnConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnConsulta.setFocusPainted(false);
        jbtnConsulta.setFocusable(false);
        jbtnConsulta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton6press.png"))); // NOI18N
        jbtnConsulta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton6roll.png"))); // NOI18N
        jbtnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConsultaActionPerformed(evt);
            }
        });
        jPanelFondoImagen.add(jbtnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        jlblFondo.setBackground(new java.awt.Color(255, 255, 255));
        jlblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Movimiento-Absoluto.jpg"))); // NOI18N
        jlblFondo.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanelFondoImagen.add(jlblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(35, 35, 35, 35);
        jPanelFondo.add(jPanelFondoImagen, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReservaActionPerformed
    
//            PreCargar carga = new PreCargar();
//            carga.setVisible(true);
//            if (carga.jProgressBar.getValue() == 100){
//                  
//            }
              moduloServicio.menuReserva Reserva = new moduloServicio.menuReserva();
                Reserva.setVisible(true);
                Reserva.setExtendedState(Reserva.MAXIMIZED_BOTH);
                this.setVisible(false);  
      
//            for(int i=0; i<=carga.x; i++)
//            {
//                PreCargar.jProgressBar.setValue(i);
//                if (i == 100)
//                {
//                dispose();
//              
//                carga.t.stop();
//                }
//           
//            }
    }//GEN-LAST:event_jbtnReservaActionPerformed

    private void jbtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarActionPerformed
        moduloRegistro.menuRegistro RegistroFunc = new  moduloRegistro.menuRegistro();
        RegistroFunc.setVisible(true);
        RegistroFunc.setExtendedState(RegistroFunc.MAXIMIZED_BOTH);
        this.setVisible(false);
         moduloRegistro.menuRegistro.jlblTituloRegistro.setText("Registro de Funcionarios");
    }//GEN-LAST:event_jbtnRegistrarActionPerformed

    private void jbtnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConsultaActionPerformed
        PreCargar carga = new PreCargar();
            carga.setVisible(true);
        
        moduloServicio.menuConsulta Consulta = new  moduloServicio.menuConsulta();
        Consulta.setVisible(true);
        this.setVisible(false);
        Consulta.setExtendedState(Consulta.MAXIMIZED_BOTH);
        moduloServicio.menuConsulta.jlblTituloConsulta.setText("Consulta Información");
        DesktopNotify.showDesktopMessage("MENSAJE DE INFORMACIÓN", 
                "PARA REALIZAR UNA CONSULTA NECESITA EL 'ID' DE LO QUE DESEA CONSULTAR ", 
                DesktopNotify.INFORMATION);
    }//GEN-LAST:event_jbtnConsultaActionPerformed

    private void jbtnRecorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRecorridoActionPerformed
        registroRecorridos regRecorridos = new registroRecorridos();
        regRecorridos.setVisible(true);
        regRecorridos.setExtendedState(regRecorridos.MAXIMIZED_BOTH);
        this.setVisible(false);
        moduloRegistro.registroRecorridos.jlblTituloRegistroTrenes.setText("Registro de Recorridos");
    }//GEN-LAST:event_jbtnRecorridoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelFondoImagen;
    public static javax.swing.JButton jbtnConsulta;
    private javax.swing.JButton jbtnRecorrido;
    private javax.swing.JButton jbtnRegistrar;
    private javax.swing.JButton jbtnReporte;
    public static javax.swing.JButton jbtnReserva;
    private javax.swing.JLabel jlblFondo;
    private javax.swing.JLabel jlblTitulo;
    // End of variables declaration//GEN-END:variables
}
