/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sist_trenes;

/**
 *
 * @author Usuario
 */
public class IntMenu extends javax.swing.JFrame {

    /**
     * Creates new form IntMenu
     */
    public IntMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnReserva = new javax.swing.JButton();
        jbtnRecorrido = new javax.swing.JButton();
        jbtnReporte = new javax.swing.JButton();
        jbtnRegistrar = new javax.swing.JButton();
        jbtnConsulta = new javax.swing.JButton();
        jlblTitulo = new javax.swing.JLabel();
        jlblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Train Ticket_26px.png"))); // NOI18N
        jbtnReserva.setText("Reservar Espacio");
        jbtnReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnReserva.setFocusable(false);
        jbtnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReservaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 174, 170, -1));

        jbtnRecorrido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Place_Marker_26px_1.png"))); // NOI18N
        jbtnRecorrido.setText("Recorridos");
        jbtnRecorrido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRecorrido.setFocusable(false);
        getContentPane().add(jbtnRecorrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 174, 130, -1));

        jbtnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/System Report_26px.png"))); // NOI18N
        jbtnReporte.setText("Reportes");
        jbtnReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnReporte.setFocusable(false);
        getContentPane().add(jbtnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        jbtnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Document_26px.png"))); // NOI18N
        jbtnRegistrar.setText("Registrar");
        jbtnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRegistrar.setFocusable(false);
        getContentPane().add(jbtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        jbtnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Questions_26px.png"))); // NOI18N
        jbtnConsulta.setText("Consulta");
        jbtnConsulta.setToolTipText("Consultar viaje");
        jbtnConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnConsulta.setFocusable(false);
        getContentPane().add(jbtnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jlblTitulo.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jlblTitulo.setForeground(java.awt.SystemColor.desktop);
        jlblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitulo.setText("TRENES DOBLE A");
        getContentPane().add(jlblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 220, 50));

        jlblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Movimiento-Absoluto.jpg"))); // NOI18N
        getContentPane().add(jlblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReservaActionPerformed
        
       menuReserva Reserva = new menuReserva();
        Reserva.setVisible(true);
    }//GEN-LAST:event_jbtnReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnConsulta;
    private javax.swing.JButton jbtnRecorrido;
    private javax.swing.JButton jbtnRegistrar;
    private javax.swing.JButton jbtnReporte;
    private javax.swing.JButton jbtnReserva;
    private javax.swing.JLabel jlblFondo;
    private javax.swing.JLabel jlblTitulo;
    // End of variables declaration//GEN-END:variables
}
